name: CI
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up php 8.3
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      - name: Install dependencies
        run: composer self-update && composer install && composer dump-autoload
      - name: Run tests and collect coverage
        run: composer test
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        env:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: dnsl48/php--hydrogen
        with:
          file: ./tests/coverage/clover/report.xml
